### ISSUE TITLE
is Hunspell class thread safe?

### ISSUE THREAD

**Issue by akonsu** [thomas-joiner/HunspellBridJ#9]
I am trying to use this library in a server code, and I hope that I can create an instance of `Hunspell` class once and use concurrently from different threads. Is this possible? Is it thread-safe? I suppose it is expensive to create `Hunspell` on each request...

**Comment by thomas-joiner** [comment]
I do not believe that it is thread-safe. The thread-safety of the Java class is dependent upon the native code. Doing some minor searching, it appears that libhunspell is not threadsafe, and as such HunspellBridJ is not threadsafe. While it might be possible to synchronize on the native library instance, this would likely cause severe performance issues since all the threads would be fighting over usage of the single instance of hunspell.

My recommendation would be to create an instance on a per-thread basis and cache it in a [`ThreadLocal`](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html?is-external=true)
